/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOS_H_RPCGEN
#define _SERVICIOS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct result_values {
	int key;
	struct {
		u_int value1_len;
		sting *value1_val;
	} value1;
	int value2;
	double value3;
};
typedef struct result_values result_values;

struct set_1_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct set_1_argument set_1_argument;

struct modify_1_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct modify_1_argument modify_1_argument;

struct copy_1_argument {
	int key1;
	int key2;
};
typedef struct copy_1_argument copy_1_argument;

#define SERVICES 99
#define SERVICESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 0
extern  enum clnt_stat init_1(int *, CLIENT *);
extern  bool_t init_1_svc(int *, struct svc_req *);
#define SET 1
extern  enum clnt_stat set_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t set_1_svc(int , char *, int , double , int *, struct svc_req *);
#define GET 2
extern  enum clnt_stat get_1(int , struct result_values *, CLIENT *);
extern  bool_t get_1_svc(int , struct result_values *, struct svc_req *);
#define MODIFY 3
extern  enum clnt_stat modify_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t modify_1_svc(int , char *, int , double , int *, struct svc_req *);
#define DELETE 4
extern  enum clnt_stat delete_1(int , int *, CLIENT *);
extern  bool_t delete_1_svc(int , int *, struct svc_req *);
#define EXIST 5
extern  enum clnt_stat exist_1(int , int *, CLIENT *);
extern  bool_t exist_1_svc(int , int *, struct svc_req *);
#define COPY 6
extern  enum clnt_stat copy_1(int , int , int *, CLIENT *);
extern  bool_t copy_1_svc(int , int , int *, struct svc_req *);
extern int services_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 0
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define SET 1
extern  enum clnt_stat set_1();
extern  bool_t set_1_svc();
#define GET 2
extern  enum clnt_stat get_1();
extern  bool_t get_1_svc();
#define MODIFY 3
extern  enum clnt_stat modify_1();
extern  bool_t modify_1_svc();
#define DELETE 4
extern  enum clnt_stat delete_1();
extern  bool_t delete_1_svc();
#define EXIST 5
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
#define COPY 6
extern  enum clnt_stat copy_1();
extern  bool_t copy_1_svc();
extern int services_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result_values (XDR *, result_values*);
extern  bool_t xdr_set_1_argument (XDR *, set_1_argument*);
extern  bool_t xdr_modify_1_argument (XDR *, modify_1_argument*);
extern  bool_t xdr_copy_1_argument (XDR *, copy_1_argument*);

#else /* K&R C */
extern bool_t xdr_result_values ();
extern bool_t xdr_set_1_argument ();
extern bool_t xdr_modify_1_argument ();
extern bool_t xdr_copy_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOS_H_RPCGEN */
